{"name": "test_Create_user_003", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: assert False", "trace": "self = <testCases.test_create_user.Test_Signup object at 0x000001C82690EF90>\nsetup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"a060d640fa51d93c3f9af4ba6ec0822b\")>\n\n    @pytest.mark.xfail\n    def test_Create_user_003(self, setup):\n    \n        Create_user = Signup_Class(setup)\n        Create_user.Click_Signup_Button()\n        Create_user.Enter_Username(\"Viplav\")\n        Create_user.Enter_Password(\"Viplav@1234\")\n        Create_user.Enter_Email(\"Viplavborkar1@gmail.com\")\n        time.sleep(3)\n        Create_user.Enter_Phoneno(\"9022515409\")\n        setup.execute_script(\"window.scrollTo(0,document.body.scrollHeight)\")  # Code for scroll to bottom\n        time.sleep(1)\n    \n        Create_user.Click_CreateUser_Button()\n        time.sleep(2)\n        if Create_user.Validation_Create_user() == \"User created successfully\":\n            print(Create_user.Validation_Create_user())\n            assert True\n        else:\n            print(\"Failed Creating user because: \", Create_user.Validation_Create_user())\n>           assert False\nE           assert False\n\ntestCases\\test_create_user.py:45: AssertionError"}, "start": 1723793434956, "stop": 1723793442541, "uuid": "f595a942-97f4-48c7-a898-8f9e0142c21e", "historyId": "4811b636241d62dacfd742a7e51fb626", "testCaseId": "4811b636241d62dacfd742a7e51fb626", "fullName": "testCases.test_create_user.Test_Signup#test_Create_user_003", "labels": [{"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "parentSuite", "value": "testCases"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "Test_Signup"}, {"name": "host", "value": "Viplav"}, {"name": "thread", "value": "12752-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.test_create_user"}]}